image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose up -d
    name: Iniciar PgAdmin
    command: |
      echo "Esperando o PgAdmin iniciar..."
      while ! nc -z localhost 5050; do
        sleep 1
      done
      echo "PgAdmin iniciado"

ports:
  - port: 5050
    onOpen: open-preview